services:
    netgen_remote_media.templating.twig.extension.remote_media:
        class: Netgen\Bundle\RemoteMediaBundle\Templating\Twig\Extension\RemoteMediaExtension
        tags:
            - { name: twig.extension }

    netgen_remote_media.templating.twig.runtime.remote_media:
        class: Netgen\Bundle\RemoteMediaBundle\Templating\Twig\Runtime\RemoteMediaRuntime
        arguments:
            - "@netgen_remote_media.provider"
            - "@netgen_remote_media.variation.resolver"
        tags:
            - { name: twig.runtime }
